services:
  payload:
    build: .
    container_name: riot-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - next:/home/node/app/.next
      - node_modules:/home/node/app/node_modules
    env_file:
      - .env
    networks:
      - riot-georgia
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: riot-mongo
    ports:
      - '3002:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    networks:
      - riot-georgia
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: pass1
  express:
    image: mongo-express
    container_name: riot-express
    ports:
      - '3001:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user1
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1
      ME_CONFIG_MONGODB_URL: mongodb://user1:pass1@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - riot-georgia
    depends_on:
      - mongo

networks:
  riot-georgia:
    name: riot-georgia
    driver: bridge

volumes:
  data:
  next:
  node_modules:
